ssh_gssapi_cleanup_global_client() needs a prototype
ok dtucker@

/usr/src/usr.bin/ssh/ssh/../ssh-gss.h:115:38: error: a function
declaration without a prototype is deprecated in all versions of C
[-Werror,-Wstrict-prototypes]
  115 | void ssh_gssapi_cleanup_global_client();
      |                                      ^
      |                                       void
1 error generated.